#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 如果使用的是 npm/yarn 且 npm 版本为 v8 及以下，就加下面的命令
# npx lint-staged

# 如果使用的是 npm/yarn 且 npm 版本为 v9 及以上，就加下面的命令
# npm exec lint-staged

# 如果使用的是 pnpm，就加下面的命令
 pnpm exec lint-staged

# ! 注意，上面的这三个命令必须根据实际情况来选择，且只能存在一个

# 获取上面脚本的退出码
exitCode="$?"
exit $exitCode
